- name: Checkout my dotfiles
  git: 
    repo: https://github.com/tarr1124/dotfiles.git
    dest: ~/dotfiles

- name: Create symlinks
  file:
    src: ~/dotfiles/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .zshrc
    - .vimrc
